apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sailsenergy-ingress
  namespace: sailsenergy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sailsenergy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sailsenergy-api
                port:
                  number: 80
